:project:
  :use_mocks: TRUE
  :build_root: build
  :test_file_prefix: test_
:paths:
  :test:
    - +:test/**
  :source:
    - ../lib/**
  :include:
    - ../lib/**
    - ../hal/**
:cmock:
  :mock_prefix: mock_
  :plugins:
    - :callback
  :mock_includes:
    - hal_traffic_lights.h
:flags:
  :test:
    :compile:
      :*: 
        - -fPIC
